version: "3"

tasks:
  default:
    deps: [install]

  install:
    desc: Install the package in development mode
    cmds:
      - pip install -e .[tests,docs]

  build:
    desc: Build distribution packages
    cmds:
      - rm -rf dist
      - python -m build

  test-pypi:
    desc: Upload packages to TestPyPI
    cmds:
      - python -m twine upload --repository testpypi dist/*.tar.gz

  clean:
    desc: Remove compiled files
    cmds:
      - rm -rf src/*.o src/*.so

  test:
    desc: Run all tests
    cmds:
      - pytest
      - cd docs && make doctest

  docs:
    desc: Build documentation
    dir: docs
    cmds:
      - make html

  autodoc:
    desc: Auto-build documentation on changes
    cmds:
      - sphinx-autobuild docs/source docs/build --watch qualpal
